# Generated by Django 4.2 on 2024-11-07 11:09

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last name"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[contacts.validators.validate_phone_number],
                        verbose_name="Номер телефону",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
            ],
        ),
    ]
